name: Documentation Build and Publish

on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages-docs
  cancel-in-progress: true

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure public/docs exists
        run: |
          mkdir -p public/docs

      - name: Build docs (Jekyll if configured)
        run: |
          if [ -f docs/_config.yml ] || [ -f docs/Gemfile ]; then
            echo "Jekyll configuration detected; building with Jekyll."
            sudo apt-get update && sudo apt-get install -y ruby-full build-essential zlib1g-dev
            gem install bundler jekyll
            (cd docs && bundle init >/dev/null 2>&1 || true)
            (cd docs && jekyll build -s . -d ../public/docs)
          else
            echo "No Jekyll config; publishing raw docs directory."
            rsync -a --delete docs/ public/docs/
          fi

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Deploy docs to Vercel (production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          ARGS=(--prod --yes --token "$VERCEL_TOKEN")
          if [ -n "$VERCEL_PROJECT_ID" ]; then
            ARGS+=(--project "$VERCEL_PROJECT_ID")
          fi
          if [ -n "$VERCEL_ORG_ID" ]; then
            ARGS+=(--scope "$VERCEL_ORG_ID")
          fi
          vercel deploy "${ARGS[@]}"


